// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQr0AveTfzhX4IBWESqzvwfhfWApi8PrY',
    appId: '1:798791617950:web:071c5b8acda6cee9b31a8f',
    messagingSenderId: '798791617950',
    projectId: 'abastecimentoflutter',
    authDomain: 'abastecimentoflutter.firebaseapp.com',
    databaseURL: 'https://abastecimentoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'abastecimentoflutter.firebasestorage.app',
    measurementId: 'G-JVXTKWV3B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH_5fa8A7QYBjgsZD9wjS-440E7E4F9Qc',
    appId: '1:798791617950:android:4c32307b6c0826deb31a8f',
    messagingSenderId: '798791617950',
    projectId: 'abastecimentoflutter',
    databaseURL: 'https://abastecimentoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'abastecimentoflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWAzikapJSl9pHC8xBcgbK78KxQRUjqs',
    appId: '1:798791617950:ios:c1abe9151fe43abbb31a8f',
    messagingSenderId: '798791617950',
    projectId: 'abastecimentoflutter',
    databaseURL: 'https://abastecimentoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'abastecimentoflutter.firebasestorage.app',
    iosBundleId: 'com.example.smartstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWAzikapJSl9pHC8xBcgbK78KxQRUjqs',
    appId: '1:798791617950:ios:c1abe9151fe43abbb31a8f',
    messagingSenderId: '798791617950',
    projectId: 'abastecimentoflutter',
    databaseURL: 'https://abastecimentoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'abastecimentoflutter.firebasestorage.app',
    iosBundleId: 'com.example.smartstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy8d-HyVoK47q21AcXAkbtkPyDaYWk8L0',
    appId: '1:798791617950:web:9528c4cfee4a8bd9b31a8f',
    messagingSenderId: '798791617950',
    projectId: 'abastecimentoflutter',
    authDomain: 'abastecimentoflutter.firebaseapp.com',
    databaseURL: 'https://abastecimentoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'abastecimentoflutter.firebasestorage.app',
    measurementId: 'G-P6481Q8N15',
  );

}